apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 131464424269.dkr.ecr.us-east-1.amazonaws.com/backend:latest   # update later
          ports:
            - containerPort: 3000
