name: DevSecOps CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Backend
      run: docker build -t backend ./backend

    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: backend
